import requests


def query_local_model(prompt: str):
    """
    Sends a prompt to a local language model server and retrieves the response.

    This function makes a POST request to a local language model server
    at the specified URL endpoint with the given prompt. The server is
    expected to return a response containing a message generated by the
    language model.

    Args:
        prompt (str): The input prompt to be sent to the language model.

    Returns:
        str: The content of the response message from the language model.
        Returns an error message if an exception occurs or if the response
        does not contain content.
    """

    url = "http://127.0.0.1:1234/v1/chat/completions"
    headers = {"Content-Type": "application/json"}

    payload = {
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 250
    }

    try:
        response = requests.post(url, headers=headers, json=payload)
        if response.status_code == 200:
            return response.json().get("choices", [{}])[0].get("message", {}).get("content", "No content returned.")
        return None
    except Exception as e:
        return f"Exception: {e}"
